"""initial

Revision ID: 2443775fb779
Revises: 
Create Date: 2026-04-12 14:05:22.125600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2443775fb779'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_id', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prompt_id')
    )
    op.create_index(op.f('ix_prompts_category'), 'prompts', ['category'], unique=False)
    op.create_table('responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_responses_record_id'), 'responses', ['record_id'], unique=True)
    op.create_index(op.f('ix_responses_run_id'), 'responses', ['run_id'], unique=False)
    op.create_index('ix_responses_run_id_model', 'responses', ['run_id', 'model'], unique=False)
    op.create_table('mentions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=128), nullable=False),
    sa.Column('matched_text', sa.String(length=256), nullable=True),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('sentence', sa.Text(), nullable=True),
    sa.Column('sentence_index', sa.Integer(), nullable=True),
    sa.Column('char_offset', sa.Integer(), nullable=True),
    sa.Column('sentiment', sa.Float(), nullable=False),
    sa.Column('sentiment_label', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['response_id'], ['responses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentions_brand'), 'mentions', ['brand'], unique=False)
    op.create_index('ix_mentions_brand_created', 'mentions', ['brand', 'created_at'], unique=False)
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=128), nullable=False),
    sa.Column('mentioned', sa.Boolean(), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.Column('first_mention_rank', sa.Integer(), nullable=True),
    sa.Column('position_score', sa.Float(), nullable=False),
    sa.Column('avg_sentiment', sa.Float(), nullable=False),
    sa.Column('sentiment_label', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['response_id'], ['responses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('response_id', 'brand', name='uq_score_response_brand')
    )
    op.create_index(op.f('ix_scores_brand'), 'scores', ['brand'], unique=False)
    op.create_index('ix_scores_brand_created', 'scores', ['brand', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scores_brand_created', table_name='scores')
    op.drop_index(op.f('ix_scores_brand'), table_name='scores')
    op.drop_table('scores')
    op.drop_index('ix_mentions_brand_created', table_name='mentions')
    op.drop_index(op.f('ix_mentions_brand'), table_name='mentions')
    op.drop_table('mentions')
    op.drop_index('ix_responses_run_id_model', table_name='responses')
    op.drop_index(op.f('ix_responses_run_id'), table_name='responses')
    op.drop_index(op.f('ix_responses_record_id'), table_name='responses')
    op.drop_table('responses')
    op.drop_index(op.f('ix_prompts_category'), table_name='prompts')
    op.drop_table('prompts')
    # ### end Alembic commands ###
